import {
  AlertTriangle,
  Badge,
  ChevronRight,
  FileInputIcon as Input,
  ImageIcon,
  MessageSquare,
  Table,
  ToggleLeft,
  Bell,
  Flag,
  Newspaper,
  BoxIcon as ButtonIcon,
  SquareIcon,
  ShoppingCart,
  MousePointerClick,
  HelpCircle,
  FootprintsIcon,
  LayoutDashboard,
  DollarSign,
  ShoppingBag,
  Grid,
  ChevronDown,
  Divide,
  PanelLeftIcon,
  BarChart2,
  ShoppingCartIcon as PaginationIcon,
} from "lucide-react"

export const categories = [
  // UI Components
  {
    name: "Alerts",
    icon: <AlertTriangle className="h-4 w-4 text-red-500" />,
    count: 5,
    href: "/components/alerts",
    featured: true,
  },
  {
    name: "Badges",
    icon: <Badge className="h-4 w-4 text-orange-500" />,
    count: 10,
    href: "/components/badges",
    featured: true,
  },
  {
    name: "Banners",
    icon: <Flag className="h-4 w-4 text-green-500" />,
    count: 6,
    href: "/components/banners",
  },
  {
    name: "Blog Cards",
    icon: <Newspaper className="h-4 w-4 text-indigo-500" />,
    count: 8,
    href: "/components/blog-cards",
  },
  {
    name: "Breadcrumbs",
    icon: <ChevronRight className="h-4 w-4 text-yellow-500" />,
    count: 10,
    href: "/components/breadcrumbs",
    featured: true,
  },
  {
    name: "Buttons",
    icon: <ButtonIcon className="h-4 w-4 text-purple-500" />,
    count: 12,
    href: "/components/buttons",
    featured: true,
  },
  {
    name: "Cards",
    icon: <SquareIcon className="h-4 w-4 text-pink-500" />,
    count: 10,
    href: "/components/cards",
    featured: true,
  },
  {
    name: "Carts",
    icon: <ShoppingCart className="h-4 w-4 text-blue-500" />,
    count: 5,
    href: "/components/carts",
  },
  {
    name: "Call to Actions",
    icon: <MousePointerClick className="h-4 w-4 text-orange-500" />,
    count: 8,
    href: "/components/ctas",
  },
  {
    name: "Dividers",
    icon: <Divide className="h-4 w-4 text-blue-500" />,
    count: 12,
    href: "/components/dividers",
  },
  {
    name: "Dropdowns",
    icon: <ChevronDown className="h-4 w-4 text-indigo-500" />,
    count: 6,
    href: "/components/dropdowns",
  },
  {
    name: "FAQs",
    icon: <HelpCircle className="h-4 w-4 text-violet-500" />,
    count: 7,
    href: "/components/faqs",
  },
  {
    name: "Forms",
    icon: <Input className="h-4 w-4 text-blue-500" />,
    count: 8,
    href: "/components/forms",
    featured: true,
  },
  {
    name: "Footers",
    icon: <FootprintsIcon className="h-4 w-4 text-gray-500" />,
    count: 8,
    href: "/components/footers",
  },
  {
    name: "Grids",
    icon: <Grid className="h-4 w-4 text-purple-500" />,
    count: 10,
    href: "/components/grids",
  },
  {
    name: "Headers",
    icon: <LayoutDashboard className="h-4 w-4 text-blue-500" />,
    count: 9,
    href: "/components/headers",
  },
  {
    name: "Media",
    icon: <ImageIcon className="h-4 w-4 text-rose-500" />,
    count: 8,
    href: "/components/media",
  },
  {
    name: "Modals",
    icon: <MessageSquare className="h-4 w-4 text-red-500" />,
    count: 8,
    href: "/components/modals",
    featured: true,
  },
  {
    name: "Pagination",
    icon: <PaginationIcon className="h-4 w-4 text-blue-500" />,
    count: 6,
    href: "/components/pagination",
  },
  {
    name: "Pricing",
    icon: <DollarSign className="h-4 w-4 text-green-500" />,
    count: 5,
    href: "/components/pricing",
  },
  {
    name: "Product Cards",
    icon: <ShoppingBag className="h-4 w-4 text-pink-500" />,
    count: 8,
    href: "/components/product-cards",
  },
  {
    name: "Side Menu",
    icon: <PanelLeftIcon className="h-4 w-4 text-indigo-500" />,
    count: 5,
    href: "/components/side-menu",
  },
  {
    name: "Stats",
    icon: <BarChart2 className="h-4 w-4 text-green-500" />,
    count: 8,
    href: "/components/stats",
  },
  {
    name: "Tables",
    icon: <Table className="h-4 w-4 text-indigo-500" />,
    count: 10,
    href: "/components/tables",
    featured: true,
  },
  {
    name: "Toggles",
    icon: <ToggleLeft className="h-4 w-4 text-pink-500" />,
    count: 6,
    href: "/components/toggles",
  },
]