import {
  AlertTriangle,
  Badge,
  ChevronRight,
  CheckSquare,
  List,
  Divide,
  ChevronDown,
  Filter,
  Grid,
  FileInputIcon as Input,
  ImageIcon,
  MessageSquare,
  Navigation,
  CreditCard,
  PanelLeftIcon,
  BarChart2,
  ListIcon as ListSteps,
  Table,
  TextIcon,
  ToggleLeft,
  PanelRightIcon,
  Bell,
  Flag,
  Newspaper,
  BoxIcon as ButtonIcon,
  SquareIcon,
  ShoppingCart,
  MousePointerClick,
  HelpCircle,
  FootprintsIcon,
  LayoutDashboard,
  DollarSign,
  ShoppingBag,
  LayoutGrid,
  Layers,
  ShoppingCartIcon as PaginationIcon,
  MinusSquare,
  RadioIcon,
  ListFilter,
} from "lucide-react"

export const categories = [
  // UI Components
  {
    name: "Alerts",
    icon: <AlertTriangle className="h-4 w-4 text-red-500" />,
    count: 5,
    href: "/components/alerts",
    featured: true,
  },
  {
    name: "Badges",
    icon: <Badge className="h-4 w-4 text-orange-500" />,
    count: 10,
    href: "/components/badges",
    featured: true,
  },
  {
    name: "Buttons",
    icon: <ButtonIcon className="h-4 w-4 text-purple-500" />,
    count: 12,
    href: "/components/buttons",
    featured: true,
  },
  {
    name: "Cards",
    icon: <SquareIcon className="h-4 w-4 text-pink-500" />,
    count: 10,
    href: "/components/cards",
    featured: true,
  },
  {
    name: "Forms",
    icon: <Input className="h-4 w-4 text-blue-500" />,
    count: 8,
    href: "/components/inputs",
    featured: true,
  },
  {
    name: "Navigation",
    icon: <Navigation className="h-4 w-4 text-green-500" />,
    count: 10,
    href: "/components/navigation",
    featured: true,
  },
  {
    name: "Tables",
    icon: <Table className="h-4 w-4 text-indigo-500" />,
    count: 10,
    href: "/components/tables",
    featured: true,
  },
  {
    name: "Modals",
    icon: <MessageSquare className="h-4 w-4 text-red-500" />,
    count: 8,
    href: "/components/modals",
    featured: true,
  },
  {
    name: "Announcements",
    icon: <Bell className="h-4 w-4 text-blue-500" />,
    count: 4,
    href: "/components/announcements",
  },
  {
    name: "Banners",
    icon: <Flag className="h-4 w-4 text-green-500" />,
    count: 6,
    href: "/components/banners",
  },
  {
    name: "Blog Cards",
    icon: <Newspaper className="h-4 w-4 text-indigo-500" />,
    count: 8,
    href: "/components/blog-cards",
  },
  {
    name: "Breadcrumbs",
    icon: <ChevronRight className="h-4 w-4 text-yellow-500" />,
    count: 10,
    href: "/components/breadcrumbs",
  },
  {
    name: "Button Groups",
    icon: <CreditCard className="h-4 w-4 text-green-500" />,
    count: 6,
    href: "/components/button-groups",
  },
  {
    name: "Carts",
    icon: <ShoppingCart className="h-4 w-4 text-blue-500" />,
    count: 5,
    href: "/components/carts",
  },
  {
    name: "Call to Actions",
    icon: <MousePointerClick className="h-4 w-4 text-orange-500" />,
    count: 8,
    href: "/components/ctas",
  },
  {
    name: "Checkboxes",
    icon: <CheckSquare className="h-4 w-4 text-green-500" />,
    count: 6,
    href: "/components/checkboxes",
  },
  {
    name: "Details Lists",
    icon: <List className="h-4 w-4 text-cyan-500" />,
    count: 8,
    href: "/components/details-lists",
  },
  {
    name: "Dividers",
    icon: <Divide className="h-4 w-4 text-blue-500" />,
    count: 12,
    href: "/components/dividers",
  },
  {
    name: "Dropdowns",
    icon: <ChevronDown className="h-4 w-4 text-indigo-500" />,
    count: 6,
    href: "/components/dropdowns",
  },
  {
    name: "FAQs",
    icon: <HelpCircle className="h-4 w-4 text-violet-500" />,
    count: 7,
    href: "/components/faqs",
  },
  {
    name: "Filters",
    icon: <Filter className="h-4 w-4 text-violet-500" />,
    count: 4,
    href: "/components/filters",
  },
  {
    name: "Footers",
    icon: <FootprintsIcon className="h-4 w-4 text-gray-500" />,
    count: 8,
    href: "/components/footers",
  },
  {
    name: "Grids",
    icon: <Grid className="h-4 w-4 text-purple-500" />,
    count: 10,
    href: "/components/grids",
  },
  {
    name: "Headers",
    icon: <LayoutDashboard className="h-4 w-4 text-blue-500" />,
    count: 9,
    href: "/components/headers",
  },
  {
    name: "Media",
    icon: <ImageIcon className="h-4 w-4 text-rose-500" />,
    count: 8,
    href: "/components/media",
  },
  {
    name: "Pagination",
    icon: <PaginationIcon className="h-4 w-4 text-blue-500" />,
    count: 6,
    href: "/components/pagination",
  },
  {
    name: "Pricing",
    icon: <DollarSign className="h-4 w-4 text-green-500" />,
    count: 5,
    href: "/components/pricing",
  },
  {
    name: "Product Cards",
    icon: <ShoppingBag className="h-4 w-4 text-pink-500" />,
    count: 8,
    href: "/components/product-cards",
  },
  {
    name: "Product Collections",
    icon: <LayoutGrid className="h-4 w-4 text-indigo-500" />,
    count: 6,
    href: "/components/product-collections",
  },
  {
    name: "Quantity Inputs",
    icon: <MinusSquare className="h-4 w-4 text-cyan-500" />,
    count: 4,
    href: "/components/quantity-inputs",
  },
  {
    name: "Radio Groups",
    icon: <RadioIcon className="h-4 w-4 text-purple-500" />,
    count: 5,
    href: "/components/radio-groups",
  },
  {
    name: "Sections",
    icon: <Layers className="h-4 w-4 text-orange-500" />,
    count: 7,
    href: "/components/sections",
  },
  {
    name: "Selects",
    icon: <ListFilter className="h-4 w-4 text-blue-500" />,
    count: 6,
    href: "/components/selects",
  },
  {
    name: "Side Menu",
    icon: <PanelLeftIcon className="h-4 w-4 text-indigo-500" />,
    count: 5,
    href: "/components/side-menu",
  },
  {
    name: "Stats",
    icon: <BarChart2 className="h-4 w-4 text-green-500" />,
    count: 8,
    href: "/components/stats",
  },
  {
    name: "Steps",
    icon: <ListSteps className="h-4 w-4 text-yellow-500" />,
    count: 6,
    href: "/components/steps",
  },
  {
    name: "Textareas",
    icon: <TextIcon className="h-4 w-4 text-purple-500" />,
    count: 5,
    href: "/components/textareas",
  },
  {
    name: "Toggles",
    icon: <ToggleLeft className="h-4 w-4 text-pink-500" />,
    count: 6,
    href: "/components/toggles",
  },
  {
    name: "Vertical Menu",
    icon: <PanelRightIcon className="h-4 w-4 text-teal-500" />,
    count: 7,
    href: "/components/vertical-menu",
  },
]
